spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_agendamento_livro_db
    username: root
    password: PQFL2024
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: true
      